openapi: 3.0.1
info:
  title: Pharmacy API
  version: 1.0.0
  description: Manage pharmacies and associate users with them for multi-tenant architecture.
security:
  - bearerAuth: []
paths:
  /pharmacies:
    get:
      summary: Get all pharmacies
      operationId: listPharmacies
      responses:
        '200':
          description: List of pharmacies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pharmacy'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new pharmacy
      operationId: createPharmacy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePharmacyRequest'
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '201':
          description: Pharmacy created

  /pharmacies/{id}:
    get:
      summary: Get pharmacy by ID
      operationId: getPharmacyById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pharmacy details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pharmacy'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found

    put:
      summary: Update pharmacy details
      operationId: updatePharmacy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePharmacyRequest'
      responses:
        '200':
          description: Updated
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    delete:
      summary: Delete pharmacy
      operationId: deletePharmacy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    Pharmacy:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        updatedBy:
          type: string
          readOnly: true
    CreatePharmacyRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        address:
          type: string
