openapi: 3.0.1
info:
  title: Reports API
  version: 1.0.0
  description: Generate reports for inventory, sales, and purchases.
security:
  - bearerAuth: []
paths:
  /reports/stock:
    get:
      summary: Get current stock levels
      operationId: getStockReport
      responses:
        '200':
          description: Stock report
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockReportItem'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /reports/sales:
    get:
      summary: Get sales report
      operationId: getSalesReport
      parameters:
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Sales report
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesReportItem'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /reports/purchases:
    get:
      summary: Get purchase report
      operationId: getPurchaseReport
      parameters:
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Purchase report
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseReportItem'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    StockReportItem:
      type: object
      properties:
        medicineId:
          type: integer
        name:
          type: string
        quantity:
          type: integer
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        updatedBy:
          type: string
          readOnly: true

    SalesReportItem:
      type: object
      properties:
        date:
          type: string
          format: date
        invoiceId:
          type: integer
        customerName:
          type: string
        totalAmount:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        updatedBy:
          type: string
          readOnly: true

    PurchaseReportItem:
      type: object
      properties:
        date:
          type: string
          format: date
        purchaseId:
          type: integer
        supplierName:
          type: string
        totalAmount:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        updatedBy:
          type: string
          readOnly: true