openapi: 3.0.1
info:
  title: Sales API
  version: 1.0.0
  description: Handle medicine sales and invoice management.
security:
  - bearerAuth: []
paths:
  /sales:
    get:
      summary: Get all sales
      operationId: listSales
      responses:
        '200':
          description: List of sales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sale'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new sale invoice
      operationId: createSale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSaleRequest'
      responses:
        '201':
          description: Sale created
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /sales/{id}:
    get:
      summary: Get sale by ID
      operationId: getSaleById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sale found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sale'
        '404':
          description: Not found
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    Sale:
      type: object
      required: [customerId, items, saleDate]
      properties:
        id:
          type: integer
        customerId:
          type: integer
        saleDate:
          type: string
          format: date-time
        totalAmount:
          type: number
          format: double
        items:
          type: array
          items:
            $ref: '#/components/schemas/SaleItem'
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        updatedBy:
          type: string
          readOnly: true
    CreateSaleRequest:
      type: object
      required:
        - customerId
        - saleDate
        - items
      properties:
        customerId:
          type: integer
        saleDate:
          type: string
          format: date-time
        totalAmount:
          type: number
          format: double
        items:
          type: array
          items:
            $ref: '#/components/schemas/CreateSaleItemRequest'
    SaleItem:
      type: object
      required: [medicineId, quantity, price]
      properties:
        medicineId:
          type: integer
        quantity:
          type: integer
        price:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        updatedBy:
          type: string
          readOnly: true
    CreateSaleItemRequest:
      type: object
      required:
        - medicineId
        - quantity
        - price
      properties:
        medicineId:
          type: integer
        quantity:
          type: integer
        price:
          type: number
          format: double

