spring:
  datasource:
    #url: jdbc:sqlserver://localhost:1433;databaseName=clickhealthpharma;encrypt=false
    url: jdbc:sqlserver://localhost:1433;databaseName=clickhealthpharma;encrypt=true;trustServerCertificate=true
    username: pharma_user
    password: Pharmacy@1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none  # use 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  application:
    name: clickhealthpharma
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  app:
    jwt:
      secret: your_jwt_secret_key
      expiration-ms: 3600000
      issuer: clickhealthpharma

